apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: flux-system
spec:
  interval: 10m
  releaseName: ollama
  targetNamespace: ollama
  chart:
    spec:
      chart: ./
      sourceRef:
        kind: GitRepository
        name: ollama
  install:
    createNamespace: true
