apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: ollama
  chart:
    spec:
      chart: ./charts/ollama
      sourceRef:
        kind: GitRepository
        name: ollama
  install:
    createNamespace: true
  valuesFrom:
    - kind: ConfigMap
      name: ollama-values
      optional: true
